"""migrate

Revision ID: f8bab12476b0
Revises: 
Create Date: 2024-07-12 10:16:14.497354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8bab12476b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('genre_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)

    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.alter_column('users_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
        batch_op.alter_column('publisher_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.SMALLINT(unsigned=True),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('ing',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('genre_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
        batch_op.alter_column('viewCount',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('reviewCount',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('uploaded',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('free_info',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('keywords',
               existing_type=mysql.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.alter_column('keywords',
               existing_type=mysql.JSON(),
               nullable=True)
        batch_op.alter_column('free_info',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(unsigned=True),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('uploaded',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
        batch_op.alter_column('score',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('reviewCount',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               nullable=True)
        batch_op.alter_column('viewCount',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               nullable=True)
        batch_op.alter_column('genre_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('ing',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(unsigned=True),
               nullable=True)
        batch_op.alter_column('publisher_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)
        batch_op.alter_column('users_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.alter_column('genre_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)

    op.create_table('images',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('src', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('novel_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], name='images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
